version: "3.7"
volumes:
  db-store:
  php-fpm-socket:
services:
  app:
    build:
      context: .
      dockerfile: ./infrastructure/php/Dockerfile
    volumes:
      - php-fpm-socket:/var/run/php-fpm:delegated
      - ./src:/work:delegated
      - ./infrastructure/php/bash/.bash_history:/root/.bash_history:delegated
      - ./infrastructure/php/bash/psysh:/root/.config/psysh:delegated
    environment:
      TZ: Asia/Tokyo
      # Laravel environment
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

  web:
    build:
      context: .
      dockerfile: ./infrastructure/nginx/Dockerfile
    ports:
      - 8080:80
    volumes:
      - php-fpm-socket:/var/run/php-fpm:delegated
      - ./src/public:/work/public:delegated
    environment:
      TZ: Asia/Tokyo
  db:
    build:
      context: .
      dockerfile: ./infrastructure/mysql/Dockerfile
    volumes:
      - db-store:/var/lib/mysql:delegated
    ports:
      - 33306:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Tokyo
