version: 2
jobs:
  test:
    docker:
      - image: circleci/php:7.3-node-browsers
      - image: circleci/mysql:5.7
    working_directory: ~/laravel_circleci_ecs
    steps:
      - checkout # ソースをgithubからworkdirにcheckoutする
      - run:
          name: Update apt-get
          command: sudo apt-get update
      - run:
          name: Libraries get
          command: >-
            sudo apt-get -y install
            software-properties-common
            libicu-dev
            libonig-dev
            libzip-dev
            unzip
            locales
            libjpeg-dev
            libfreetype6-dev
            libjpeg62-turbo-dev
            libpng-dev
            g++
            gcc
      - run:
          name: Docker php extensions install
          command: >-
            sudo docker-php-ext-install
            pdo_mysql
            mbstring
            zip
            bcmath
            gd
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "src/composer.lock" }}
            - v1-dependencies-
      - run:
          name: Install PHP libraries
          command: composer install -n --prefer-dist
          working_directory: src/
      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "src/composer.lock" }}
      - run:
          name: Create Environment file
          command: mv .env.testing .env && php artisan key:generate
          working_directory: src/
      - run:
          name: DB Migration
          command: php artisan migrate && php artisan db:seed
          working_directory: src/
      - run:
          name: Run PHPUnit
          command: php artisan test
          working_directory: src/

  bulid_image_and_push:
    docker:
      - image: circleci/php:7.3.9-fpm
    working_directory: ~/laravel_circleci_ecs
    steps:
      - checkout
      - run:
          name: setup Laravel # envをproduction用のものに変更&権限設定 ln -s .env.production .env
          command: |
            sudo chmod -R 777 storage bootstrap/cache
      - run:
          name: composer install
          command: composer install -n --prefer-dist
      - run: # configファイルをキャッシュ
          name: create config cache
          command: php artisan config:cache
      - run:
          name: build container # PHPコンテナをビルド
          command: |
            docker build --no-cache -t sample-php-fpm:latest --build-arg TZ=${TZ} -f ./docker/php/Dockerfile .
            docker build --no-cache -t sample-nginx:latest --build-arg TZ=${TZ} -f ./docker/web/Dockerfile .
      - run:
          name: install aws cli # コマンドラインからAWSを操作するためにaws-cliをインストール
          command: |
            curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
            sudo python get-pip.py
            sudo pip install awscli
      - run:
          name: push docker image # ECRにコンテナイメージをpush
          command: |
            aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin ${AWS_ECR_ACCOUNT_URL}
            docker push ${AWS_ECR_ACCOUNT_URL}/sample-php-fpm:latest
            docker push ${AWS_ECR_ACCOUNT_URL}/sample-nginx:latest

workflows:
  version: 2
  test:
    jobs:
      - test
      - bulid_image_and_push:
          requires:
            - test
          filters:
            branches:
              only: master
      # - deploy:
      #     requires:
      #       - build_image
      #     filters:
      #       branches:
      #         only: master
