version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers
      - image: circleci/mysql:5.7
    working_directory: ~/laravel_circleci_ecs
    steps:
      - checkout # ソースをgithubからworkdirにcheckoutする
      - run:
          name: Update apt-get
          command: sudo apt-get update
      - run:
          name: Libraries get
          command: >-
            sudo apt-get -y install
            software-properties-common
            libicu-dev
            libonig-dev
            libzip-dev
            unzip
            locales
            libjpeg-dev
            libfreetype6-dev
            libjpeg62-turbo-dev
            libpng-dev
            g++
            gcc
      - run:
          name: Docker php extensions install
          command: >-
            sudo docker-php-ext-install
            pdo_mysql
            mbstring
            zip
            bcmath
            gd
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "src/composer.lock" }}
            - v1-dependencies-
      - run:
          name: Install PHP libraries
          command: composer install -n --prefer-dist
          working_directory: src/
      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "src/composer.lock" }}
      - run:
          name: Create Environment file
          command: mv .env.testing .env && php artisan key:generate
          working_directory: src/
      - run:
          name: DB Migration
          command: php artisan migrate && php artisan db:seed
          working_directory: src/
      - run:
          name: Run PHPUnit
          command: php artisan test
          working_directory: src/
